// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEB55tuOs4qNJs34YzkCikdY3YwN8uRPs',
    appId: '1:1094652614875:web:aa6f55f7c1aa47c99294fe',
    messagingSenderId: '1094652614875',
    projectId: 'manage-money-3aa5f',
    authDomain: 'manage-money-3aa5f.firebaseapp.com',
    storageBucket: 'manage-money-3aa5f.firebasestorage.app',
    measurementId: 'G-3GXS4KHD14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9JVf2ZwkxZtIPC998KqtPelpSXAgj2Pg',
    appId: '1:1094652614875:android:d92dd0583f5a13969294fe',
    messagingSenderId: '1094652614875',
    projectId: 'manage-money-3aa5f',
    storageBucket: 'manage-money-3aa5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAte3WMFHLXDKFsnf5G3a-f2LvhJ3oc1HM',
    appId: '1:1094652614875:ios:30318689d446579a9294fe',
    messagingSenderId: '1094652614875',
    projectId: 'manage-money-3aa5f',
    storageBucket: 'manage-money-3aa5f.firebasestorage.app',
    iosBundleId: 'com.jyb.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAte3WMFHLXDKFsnf5G3a-f2LvhJ3oc1HM',
    appId: '1:1094652614875:ios:30318689d446579a9294fe',
    messagingSenderId: '1094652614875',
    projectId: 'manage-money-3aa5f',
    storageBucket: 'manage-money-3aa5f.firebasestorage.app',
    iosBundleId: 'com.jyb.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEB55tuOs4qNJs34YzkCikdY3YwN8uRPs',
    appId: '1:1094652614875:web:dd70ac3d19e2168d9294fe',
    messagingSenderId: '1094652614875',
    projectId: 'manage-money-3aa5f',
    authDomain: 'manage-money-3aa5f.firebaseapp.com',
    storageBucket: 'manage-money-3aa5f.firebasestorage.app',
    measurementId: 'G-X4PY8221ML',
  );
}
